import type { DietaryItem } from "@/constants/types"

export const RecommendedMeals: DietaryItem[] = [
  {
    name: "Greek Yogurt with Berries",
    time_name: "breakfast",
    time: "07:30",
    fats: 3,
    proteins: 20,
    carbohydrates: 25,
    completed: false,
  },
  {
    name: "Avocado Toast with Egg",
    time_name: "breakfast",
    time: "08:00",
    fats: 15,
    proteins: 15,
    carbohydrates: 20,
    completed: false,
  },
  {
    name: "Oatmeal with Nuts and Fruits",
    time_name: "breakfast",
    time: "07:45",
    fats: 10,
    proteins: 8,
    carbohydrates: 30,
    completed: false,
  },
  {
    name: "Protein Pancakes",
    time_name: "breakfast",
    time: "08:15",
    fats: 8,
    proteins: 25,
    carbohydrates: 30,
    completed: false,
  },
  {
    name: "Spinach and Feta Omelette",
    time_name: "breakfast",
    time: "08:30",
    fats: 18,
    proteins: 20,
    carbohydrates: 5,
    completed: false,
  },
  {
    name: "Quinoa Salad with Grilled Chicken",
    time_name: "lunch",
    time: "12:30",
    fats: 10,
    proteins: 30,
    carbohydrates: 35,
    completed: false,
  },
  {
    name: "Tuna Wrap with Vegetables",
    time_name: "lunch",
    time: "13:00",
    fats: 12,
    proteins: 25,
    carbohydrates: 30,
    completed: false,
  },
  {
    name: "Vegetable Stir-Fry with Tofu",
    time_name: "lunch",
    time: "12:45",
    fats: 15,
    proteins: 20,
    carbohydrates: 25,
    completed: false,
  },
  {
    name: "Lentil Soup with Whole Grain Bread",
    time_name: "lunch",
    time: "13:15",
    fats: 8,
    proteins: 18,
    carbohydrates: 40,
    completed: false,
  },
  {
    name: "Grilled Salmon with Sweet Potato",
    time_name: "lunch",
    time: "13:30",
    fats: 20,
    proteins: 30,
    carbohydrates: 25,
    completed: false,
  },
  {
    name: "Salmon with Sweet Potato",
    time_name: "dinner",
    time: "19:00",
    fats: 15,
    proteins: 25,
    carbohydrates: 30,
    completed: false,
  },
  {
    name: "Grilled Chicken with Quinoa and Vegetables",
    time_name: "dinner",
    time: "19:30",
    fats: 12,
    proteins: 30,
    carbohydrates: 35,
    completed: false,
  },
  {
    name: "Beef Stir-Fry with Brown Rice",
    time_name: "dinner",
    time: "19:15",
    fats: 18,
    proteins: 28,
    carbohydrates: 40,
    completed: false,
  },
  {
    name: "Baked Cod with Roasted Vegetables",
    time_name: "dinner",
    time: "19:45",
    fats: 10,
    proteins: 25,
    carbohydrates: 20,
    completed: false,
  },
  {
    name: "Vegetarian Chili with Cornbread",
    time_name: "dinner",
    time: "19:00",
    fats: 15,
    proteins: 20,
    carbohydrates: 45,
    completed: false,
  },
  {
    name: "Protein Smoothie",
    time_name: "snack",
    time: "15:30",
    fats: 5,
    proteins: 20,
    carbohydrates: 25,
    completed: false,
  },
  {
    name: "Apple Slices with Almond Butter",
    time_name: "snack",
    time: "10:30",
    fats: 15,
    proteins: 7,
    carbohydrates: 15,
    completed: false,
  },
  {
    name: "Carrot Sticks with Hummus",
    time_name: "snack",
    time: "16:00",
    fats: 8,
    proteins: 5,
    carbohydrates: 15,
    completed: false,
  },
  {
    name: "Greek Yogurt with Granola",
    time_name: "snack",
    time: "11:00",
    fats: 6,
    proteins: 15,
    carbohydrates: 20,
    completed: false,
  },
  {
    name: "Hard-Boiled Eggs",
    time_name: "snack",
    time: "15:00",
    fats: 10,
    proteins: 12,
    carbohydrates: 1,
    completed: false,
  },
  {
    name: "Banana with Peanut Butter",
    time_name: "pre-workout",
    time: "14:00",
    fats: 8,
    proteins: 4,
    carbohydrates: 30,
    completed: false,
  },
  {
    name: "Whole Grain Toast with Avocado",
    time_name: "pre-workout",
    time: "14:30",
    fats: 15,
    proteins: 5,
    carbohydrates: 20,
    completed: false,
  },
  {
    name: "Oatmeal with Berries",
    time_name: "pre-workout",
    time: "14:15",
    fats: 3,
    proteins: 6,
    carbohydrates: 30,
    completed: false,
  },
  {
    name: "Energy Bar",
    time_name: "pre-workout",
    time: "14:45",
    fats: 9,
    proteins: 10,
    carbohydrates: 30,
    completed: false,
  },
  {
    name: "Rice Cakes with Almond Butter",
    time_name: "pre-workout",
    time: "14:00",
    fats: 10,
    proteins: 5,
    carbohydrates: 22,
    completed: false,
  },
  {
    name: "Chocolate Protein Shake",
    time_name: "post-workout",
    time: "16:30",
    fats: 3,
    proteins: 25,
    carbohydrates: 20,
    completed: false,
  },
  {
    name: "Grilled Chicken and Sweet Potato",
    time_name: "post-workout",
    time: "17:00",
    fats: 5,
    proteins: 30,
    carbohydrates: 30,
    completed: false,
  },
  {
    name: "Tuna Salad with Whole Grain Crackers",
    time_name: "post-workout",
    time: "16:45",
    fats: 10,
    proteins: 25,
    carbohydrates: 20,
    completed: false,
  },
  {
    name: "Greek Yogurt with Fruit and Granola",
    time_name: "post-workout",
    time: "17:15",
    fats: 6,
    proteins: 20,
    carbohydrates: 35,
    completed: false,
  },
  {
    name: "Cottage Cheese with Pineapple",
    time_name: "post-workout",
    time: "16:30",
    fats: 4,
    proteins: 25,
    carbohydrates: 20,
    completed: false,
  },
]

