import type { DietaryItem, Exercise, MealItem, WorkoutData } from "@/constants/types"

export const RecommendedMeals: MealItem[] = [
  {
    _id:"1",
    calories: 300,
    name: "Greek Yogurt with Berries",
    time_name: "breakfast",
    time: "07:30",
    fats: 3,
    proteins: 20,
    carbohydrates: 25,
    completed: false,
  },
  {
    _id:"1",
    calories: 300,
    name: "Avocado Toast with Egg",
    time_name: "breakfast",
    time: "08:00",
    fats: 15,
    proteins: 15,
    carbohydrates: 20,
    completed: false,
  },
  {
    _id:"1",
    calories: 300,
    name: "Oatmeal with Nuts and Fruits",
    time_name: "breakfast",
    time: "07:45",
    fats: 10,
    proteins: 8,
    carbohydrates: 30,
    completed: false,
  },
  {
    _id:"1",
    calories: 300,
    name: "Protein Pancakes",
    time_name: "breakfast",
    time: "08:15",
    fats: 8,
    proteins: 25,
    carbohydrates: 30,
    completed: false,
  },
  {
    _id:"1",
    calories: 300,
    name: "Spinach and Feta Omelette",
    time_name: "breakfast",
    time: "08:30",
    fats: 18,
    proteins: 20,
    carbohydrates: 5,
    completed: false,
  },
  {
    _id:"1",
    calories: 300,
    name: "Quinoa Salad with Grilled Chicken",
    time_name: "lunch",
    time: "12:30",
    fats: 10,
    proteins: 30,
    carbohydrates: 35,
    completed: false,
  },
  {
    _id:"1",
    calories: 300,
    name: "Tuna Wrap with Vegetables",
    time_name: "lunch",
    time: "13:00",
    fats: 12,
    proteins: 25,
    carbohydrates: 30,
    completed: false,
  },
  {
    _id:"1",
    calories: 300,
    name: "Vegetable Stir-Fry with Tofu",
    time_name: "lunch",
    time: "12:45",
    fats: 15,
    proteins: 20,
    carbohydrates: 25,
    completed: false,
  },
  {
    _id:"1",
    calories: 300,
    name: "Lentil Soup with Whole Grain Bread",
    time_name: "lunch",
    time: "13:15",
    fats: 8,
    proteins: 18,
    carbohydrates: 40,
    completed: false,
  },
  {
    _id:"1",
    calories: 300,
    name: "Grilled Salmon with Sweet Potato",
    time_name: "lunch",
    time: "13:30",
    fats: 20,
    proteins: 30,
    carbohydrates: 25,
    completed: false,
  },
  {
    _id:"1",
    calories: 300,
    name: "Salmon with Sweet Potato",
    time_name: "dinner",
    time: "19:00",
    fats: 15,
    proteins: 25,
    carbohydrates: 30,
    completed: false,
  },
  {
    _id:"1",
    calories: 300,
    name: "Grilled Chicken with Quinoa and Vegetables",
    time_name: "dinner",
    time: "19:30",
    fats: 12,
    proteins: 30,
    carbohydrates: 35,
    completed: false,
  },
  {
    _id:"1",
    calories: 300,
    name: "Beef Stir-Fry with Brown Rice",
    time_name: "dinner",
    time: "19:15",
    fats: 18,
    proteins: 28,
    carbohydrates: 40,
    completed: false,
  },
  {
    _id:"1",
    calories: 300,
    name: "Baked Cod with Roasted Vegetables",
    time_name: "dinner",
    time: "19:45",
    fats: 10,
    proteins: 25,
    carbohydrates: 20,
    completed: false,
  },
  {
    _id:"1",
    calories: 300,
    name: "Vegetarian Chili with Cornbread",
    time_name: "dinner",
    time: "19:00",
    fats: 15,
    proteins: 20,
    carbohydrates: 45,
    completed: false,
  },
  {
    _id:"1",
    calories: 300,
    name: "Protein Smoothie",
    time_name: "snack",
    time: "15:30",
    fats: 5,
    proteins: 20,
    carbohydrates: 25,
    completed: false,
  },
  {
    _id:"1",
    calories: 300,
    name: "Apple Slices with Almond Butter",
    time_name: "snack",
    time: "10:30",
    fats: 15,
    proteins: 7,
    carbohydrates: 15,
    completed: false,
  },
  {
    _id:"1",
    calories: 300,
    name: "Carrot Sticks with Hummus",
    time_name: "snack",
    time: "16:00",
    fats: 8,
    proteins: 5,
    carbohydrates: 15,
    completed: false,
  },
  {
    _id:"1",
    calories: 300,
    name: "Greek Yogurt with Granola",
    time_name: "snack",
    time: "11:00",
    fats: 6,
    proteins: 15,
    carbohydrates: 20,
    completed: false,
  },
  {
    _id:"1",
    calories: 300,
    name: "Hard-Boiled Eggs",
    time_name: "snack",
    time: "15:00",
    fats: 10,
    proteins: 12,
    carbohydrates: 1,
    completed: false,
  },
  {
    _id:"1",
    calories: 300,
    name: "Banana with Peanut Butter",
    time_name: "pre-workout",
    time: "14:00",
    fats: 8,
    proteins: 4,
    carbohydrates: 30,
    completed: false,
  },
  {
    _id:"1",
    calories: 300,
    name: "Whole Grain Toast with Avocado",
    time_name: "pre-workout",
    time: "14:30",
    fats: 15,
    proteins: 5,
    carbohydrates: 20,
    completed: false,
  },
  {
    _id:"1",
    calories: 300,
    name: "Oatmeal with Berries",
    time_name: "pre-workout",
    time: "14:15",
    fats: 3,
    proteins: 6,
    carbohydrates: 30,
    completed: false,
  },
  {
    _id:"1",
    calories: 300,
    name: "Energy Bar",
    time_name: "pre-workout",
    time: "14:45",
    fats: 9,
    proteins: 10,
    carbohydrates: 30,
    completed: false,
  },
  {
    _id:"1",
    calories: 300,
    name: "Rice Cakes with Almond Butter",
    time_name: "pre-workout",
    time: "14:00",
    fats: 10,
    proteins: 5,
    carbohydrates: 22,
    completed: false,
  },
  {
    _id:"1",
    calories: 300,
    name: "Chocolate Protein Shake",
    time_name: "post-workout",
    time: "16:30",
    fats: 3,
    proteins: 25,
    carbohydrates: 20,
    completed: false,
  },
  {
    _id:"1",
    calories: 300,
    name: "Grilled Chicken and Sweet Potato",
    time_name: "post-workout",
    time: "17:00",
    fats: 5,
    proteins: 30,
    carbohydrates: 30,
    completed: false,
  },
  {_id:"1",
    calories: 300,
    name: "Tuna Salad with Whole Grain Crackers",
    time_name: "post-workout",
    time: "16:45",
    fats: 10,
    proteins: 25,
    carbohydrates: 20,
    completed: false,
  },
  {
    _id:"1",
    calories: 300,
    name: "Greek Yogurt with Fruit and Granola",
    time_name: "post-workout",
    time: "17:15",
    fats: 6,
    proteins: 20,
    carbohydrates: 35,
    completed: false,
  },
  {
    _id:"1",
    calories: 300,
    name: "Cottage Cheese with Pineapple",
    time_name: "post-workout",
    time: "16:30",
    fats: 4,
    proteins: 25,
    carbohydrates: 20,
    completed: false,
  },
]


export const sleepContent = [
  {
    title: "Bed-Time Stories",
    description: "Techniques, Benefits, and a Beginner's How-To",
    image: "https://example.com/bedtime-stories.jpg",
  },
  {
    title: "Music For Sleep",
    description: "Techniques, Benefits, and a Beginner's How-To",
    image: "https://example.com/sleep-music.jpg",
  },
]



export const MENTAL_HEALTH_ACTIVITIES = [
  { id: 1, label: 'Mindfulness', checked: false },
  { id: 2, label: 'Gratitude', checked: false },
  { id: 3, label: 'Self-Care', checked: false },
  { id: 4, label: 'Cared for Someone', checked: false },
  { id: 5, label: 'Met Loved Ones', checked: false },
  { id: 6, label: 'Exercised', checked: false },
  { id: 7, label: 'Did Something Fun', checked: false },
];

export const EMOTIONS = [
  { id: 1, label: 'Happy', emoji: require('@/assets/images/MentalWellness/emotions/happy.png') },
  { id: 2, label: 'Sad', emoji: require('@/assets/images/MentalWellness/emotions/sad.png') },
  { id: 3, label: 'Content', emoji: require('@/assets/images/MentalWellness/emotions/content.png') },
  { id: 4, label: 'Anxious', emoji: require('@/assets/images/MentalWellness/emotions/anxious.png') },
];




// Sample Workout Data
export const sampleWeeklyWorkouts: Exercise[][] = [
  // Monday
  [
    {
      id: "1",
      name: "High-Intensity Interval Training",
      type: "hit",
      duration: { minutes: 30, seconds: 0 },
      repetitions: 5,
      caloriesBurned: 350,
      completed: false
    },
    {
      id: "2", 
      name: "Core Strength Workout",
      type: "strength",
      duration: { minutes: 25, seconds: 0 },
      repetitions: 3,
      caloriesBurned: 200,
      completed: true
    }
  ],
  // Tuesday - More sample workouts for each day
  ...Array(6).fill([
    {
      id: "3",
      name: "Cardio Run",
      type: "cardio",
      duration: { minutes: 45, seconds: 0 },
      repetitions: 1,
      caloriesBurned: 400,
      completed: false
    },
    {
      id: "4",
      name: "Yoga Flow",
      type: "yoga",
      duration: { minutes: 35, seconds: 0 },
      repetitions: 1,
      caloriesBurned: 150,
      completed: false
    }
  ])
]
